HMM fix resampling state sequence, updated documentation for developers
mad-lab-fau/gaitmap pull request #62
Opened 2024-04-17 13:37 UTC by Aksei

@AKuederle @HaMora 
The resampling of the state sequence for the HMM is now fixed, tests are adapted. 
Resampling is also tested for cases in which target_sample_rate is not a multiple of the Roth HMM sample rate.
Can you please review the changes?

2024-04-17 13:47 UTC, AKuederle requested changes
See one comment. And can you add a Changelog entry with a link to this PR?

2024-04-17 13:47 UTC, AKuederle commented on gaitmap_mad/gaitmap_mad/stride_segmentation/hmm/_hmm_feature_transform.py
> +        self, state_sequence: np.ndarray, data: np.array, *, sampling_rate_hz: float
Can you unify the call signature of the base class with your implementaiton? The actual implementation does not get sampling_rate_hz as parameter. So remove it here as well

2024-04-19 08:00 UTC, Aksei commented
@AKuederle 
I addressed all your comments. Can you check again?

2024-04-19 08:17 UTC, AKuederle approved these changes

2024-04-19 09:00 UTC, merged